board: [seeeduino_xiao_ble]
shield: [chippy_left, chippy_right]
include:
  - board: seeeduino_xiao_ble
    shield: chippy_left nice_view
    artifact-name: chippy_left
  - board: seeeduino_xiao_ble
    shield: chippy_right nice_view
    artifact-name: chippy_right
